server:
  port: ${SERVER_PORT:8080}

mockidp:
  ldap:
    base-dn: "${MOCKIDP_LDAP_BASE_DN:dc=msil,dc=co,dc=in}"
    listener-port: ${MOCKIDP_LDAP_PORT:8389}
    ldif: "${MOCKIDP_LDAP_LDIF:classpath:setup.ldif}"
    manager-dn: "${MOCKIDP_LDAP_MANAGER_DN:cn=Directory Manager}"
    manager-password: "${MOCKIDP_LDAP_MANAGER_PASSWORD:password}"
  rate-limit:
    enabled: ${MOCKIDP_RATE_LIMIT_ENABLED:true}
    max-requests: ${MOCKIDP_RATE_LIMIT_MAX_REQUESTS:5}
    duration-seconds: ${MOCKIDP_RATE_LIMIT_DURATION_SECONDS:60}
  jwt:
    expiry-seconds: ${MOCKIDP_JWT_EXPIRY_SECONDS:3600}


