services:

  # 1. Mock Identity Provider & LDAP Server
  idp-service:
    build:
      context: ./IDP_Service
      dockerfile: Dockerfile
    container_name: idp-service
    ports:
      - "8080:8080"
      - "8389:8389"
    env_file:
      - ./IDP_Service/.env
    volumes:
      - ./IDP_Service/setup.ldif:/app/setup.ldif
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/.well-known/jwks.json"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  # 2. Portal Backend modular monolith
  backend-server:
    build:
      context: ./ITEA_Dept_Portal_Backend
      dockerfile: Dockerfile
    container_name: itea_dept_portal_backend
    ports:
      - "8081:8081"
    env_file:
      - ./ITEA_Dept_Portal_Backend/.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres.wvodzeuwfbbqszztwjgx
      - SPRING_DATASOURCE_PASSWORD=,cwjwpt8UAetzA@
      - MOCKIDP_URL=http://idp-service:8080
    depends_on:
      idp-service:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8081"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  # 3. React Frontend served via Nginx
  frontend-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: itea_dept_portal_frontend
    ports:
      - "3000:80"
    depends_on:
      backend-server:
        condition: service_healthy
    restart: always

