spring.application.name=ITEA_Dept_Portal_Backend
server.port=${PORT:8081}

# PostgreSQL Database settings
spring.datasource.url=${SUPABASE_DB_URL}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${SUPABASE_DB_USERNAME}
spring.datasource.password=${SUPABASE_DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# Supabase S3 Storage
supabase.s3.endpointUrl=${SUPABASE_S3_ENDPOINT}
supabase.s3.accessKey=${SUPABASE_S3_ACCESS_KEY}
supabase.s3.secretKey=${SUPABASE_S3_SECRET_KEY}
supabase.s3.region=${SUPABASE_S3_REGION:auto}
